services:
  challenge-api:
    image: redteamsubnet61/rest-bv-challenge:1.0.4
    container_name: bot_virus_v1
    build:
      context: ./src/bv_challenge/challenge
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - bot-virus-challenge-net
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      BV_CHALLENGE_API_PORT: ${BV_CHALLENGE_API_PORT:-10001}
      DOCKER_HOST: unix:///docker-socket/docker.sock
      CHALLENGE_HTTPS_PROXY_PORT: ${CHALLENGE_HTTPS_PROXY_PORT:-10443}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/configs/rest-bv-challenge:${BV_CHALLENGE_API_CONFIGS_DIR:-/etc/rest-bv-challenge}"
      - "./volumes/storage/rest-bv-challenge/logs:${BV_CHALLENGE_API_LOGS_DIR:-/var/log/rest-bv-challenge}"
      - "./volumes/storage/rest-bv-challenge/data:${BV_CHALLENGE_API_DATA_DIR:-/var/lib/rest-bv-challenge}"
      - "bot-runner-dind-socket:/docker-socket"
      - "bot-commit:/commit"
    ports:
      - "${BV_CHALLENGE_API_PORT:-10001}:${BV_CHALLENGE_API_PORT:-10001}"
  bot-runner-dind:
    image: redteamsubnet61/bot_virus_bot_runner_dind:latest
    build:
      context: ./src/modules/bv-bot-runner
      dockerfile: Dockerfile.dind
    restart: unless-stopped
    networks:
      - bot-virus-challenge-net
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
      CHALLENGE_HTTPS_PROXY_PORT: ${CHALLENGE_HTTPS_PROXY_PORT:-10443}
    volumes:
      - "bot-runner-dind-socket:/docker-socket"
      - "bot-runner-dind-data:/var/lib/docker"
      - "bot-commit:/commit:ro"
networks:
  bot-virus-challenge-net:
    name: bot-virus-challenge-net
    driver: bridge
volumes:
  bot-runner-dind-socket:
  bot-runner-dind-data:
  bot-commit:
