services:
  bot:
    image: bot:latest
    build:
      context: .
      platforms:
        - linux/amd64
    environment:
      TERM: ${TERM:-xterm}
      TZ: UTC
      BV_WEB_URL: ${BV_WEB_URL:-https://172.17.0.1:10001/_web}
      BV_ACTION_LIST: ${BV_ACTION_LIST}
      BV_SESSION_COUNT: ${BV_SESSION_COUNT}
    env_file:
      - path: .env
        required: false
    tty: true
